/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clerk;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import manager.AddEmployee;

/**
 *
 * @author HP
 */
public class PaymentForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterStudent
     */
    public PaymentForm() {
        initComponents();
        lblid.setText(RegisterStudent.studentID);
        setValues();
    }
    public static String type="";
    public static String tot="";
    public static String payment="";
    public static String tobepaid="";
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        btnpayment = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttot = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpayment = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbfull = new javax.swing.JRadioButton();
        rbinstallment = new javax.swing.JRadioButton();
        txttobepaid = new javax.swing.JTextField();
        btnpayments = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        txtreg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel2.setText("Student ID");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setText("Total Amount");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, 30));

        txttot.setEditable(false);
        txttot.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jPanel4.add(txttot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 100, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel5.setText("Payment");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 70, 20));

        txtpayment.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaymentActionPerformed(evt);
            }
        });
        jPanel4.add(txtpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel7.setText("To Be Paid");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 80, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Payment Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 17))); // NOI18N

        btnpayment.add(rbfull);
        rbfull.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        rbfull.setText("Full");
        rbfull.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbfullFocusGained(evt);
            }
        });
        rbfull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfullActionPerformed(evt);
            }
        });

        btnpayment.add(rbinstallment);
        rbinstallment.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        rbinstallment.setText("Installment");
        rbinstallment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbinstallmentFocusGained(evt);
            }
        });
        rbinstallment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbinstallmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(rbfull)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(rbinstallment)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbfull)
                    .addComponent(rbinstallment))
                .addGap(16, 16, 16))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 240, 80));

        txttobepaid.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jPanel4.add(txttobepaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 110, 30));

        btnpayments.setBackground(new java.awt.Color(0, 102, 0));
        btnpayments.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnpayments.setForeground(new java.awt.Color(255, 255, 255));
        btnpayments.setText("Pay Now");
        btnpayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaymentsActionPerformed(evt);
            }
        });
        jPanel4.add(btnpayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 101, 40));

        lblid.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jPanel4.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 100, 20));

        txtreg.setEditable(false);
        txtreg.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jPanel4.add(txtreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel4.setText("Registration Fee");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 30));

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setBackground(new java.awt.Color(0, 102, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payment Details");

        btncancel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 670, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void setValues(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/learnersms", "root","");
            
            String SQL="SELECT * FROM paymentinfo WHERE vehicleCategory=?";
            PreparedStatement pstm=conn.prepareStatement(SQL);
            pstm.setObject(1,RegisterStudent.category);
            ResultSet rst=pstm.executeQuery();
            if (rst.next()) {
                tot=rst.getString(2);
                txttot.setText(tot);
                txtreg.setText(rst.getString(3));
            }else{
                JOptionPane.showMessageDialog(this, "Error in the category!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnpaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaymentsActionPerformed
        if(!txtpayment.getText().equals(null)){
        payment=txtpayment.getText();
        tobepaid=txttobepaid.getText();
         JOptionPane.showMessageDialog(this, "Payment successfully Done!!!");
         this.hide();
        }else{
            JOptionPane.showMessageDialog(this, "Please enter you payment amount!!!");
        }
    }//GEN-LAST:event_btnpaymentsActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        this.hide();
    }//GEN-LAST:event_btncancelActionPerformed

    private void txtpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaymentActionPerformed
        if(rbfull.isSelected()){
            type="full";
            txttobepaid.setText("");
        }else if(rbinstallment.isSelected()){
            type="installment";
            double total=Double.parseDouble(txttot.getText());
            double pay=Double.parseDouble(txtpayment.getText());
            double tobepaid=total-(pay+2000.00);
            txttobepaid.setText(tobepaid+"");
            System.out.println(tobepaid);
        }else{
            JOptionPane.showMessageDialog(this, "Please select your payment type!!!");
        }
    }//GEN-LAST:event_txtpaymentActionPerformed

    private void rbinstallmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbinstallmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbinstallmentActionPerformed

    private void rbfullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfullActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbfullActionPerformed

    private void rbfullFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbfullFocusGained
            type="full";
            txttobepaid.setText("");
            txtpayment.setText(txttot.getText());
    }//GEN-LAST:event_rbfullFocusGained

    private void rbinstallmentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbinstallmentFocusGained
        txttobepaid.setText("");
        txtpayment.setText("");
    }//GEN-LAST:event_rbinstallmentFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.ButtonGroup btnpayment;
    private javax.swing.JButton btnpayments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblid;
    private javax.swing.JRadioButton rbfull;
    private javax.swing.JRadioButton rbinstallment;
    private javax.swing.JTextField txtpayment;
    private javax.swing.JTextField txtreg;
    private javax.swing.JTextField txttobepaid;
    private javax.swing.JTextField txttot;
    // End of variables declaration//GEN-END:variables
}
