/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clerk;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import manager.AddEmployee;

/**
 *
 * @author HP
 */
public class RegisterStudent extends javax.swing.JFrame {

    /**
     * Creates new form RegisterStudent
     */
    public RegisterStudent() {
        initComponents();
        lblid.setText(getStudentID());
        lbldate.setText(LocalDate.now()+"");
    }

    public static String studentID="";
    public static String category="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        btngrpgender = new javax.swing.ButtonGroup();
        btngrpcategory = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtconno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtheight = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbbldgrp = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtweight = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbmale = new javax.swing.JRadioButton();
        rbfemale = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbA = new javax.swing.JRadioButton();
        rbC = new javax.swing.JRadioButton();
        rbB = new javax.swing.JRadioButton();
        btnregister = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnpayments = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        btnclear1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(1040, 620));
        jPanel4.setPreferredSize(new java.awt.Dimension(1040, 620));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Student ID");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 110, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Full Name");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 90, 20));

        txtname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel4.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 370, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Address");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 70, 20));

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 350, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Contact No");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 110, 20));

        txtconno.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtconno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconnoActionPerformed(evt);
            }
        });
        jPanel4.add(txtconno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 160, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("NIC");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 50, 30));

        txtheight.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel4.add(txtheight, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 60, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Blood Group");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 120, 20));

        cmbbldgrp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cmbbldgrp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        jPanel4.add(cmbbldgrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 107, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Height(ft)");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 100, 30));

        txtweight.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel4.add(txtweight, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 60, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 20))); // NOI18N

        rbmale.setBackground(new java.awt.Color(204, 204, 255));
        btngrpgender.add(rbmale);
        rbmale.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbmale.setText("Male");
        rbmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmaleActionPerformed(evt);
            }
        });

        rbfemale.setBackground(new java.awt.Color(204, 204, 255));
        btngrpgender.add(rbfemale);
        rbfemale.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbfemale.setText("Female");
        rbfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfemaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(rbmale)
                .addGap(26, 26, 26)
                .addComponent(rbfemale)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbmale)
                    .addComponent(rbfemale))
                .addGap(16, 16, 16))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Weight(kg)");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 110, 30));

        txtnic.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel4.add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 170, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Vehicle Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 20))); // NOI18N

        rbA.setBackground(new java.awt.Color(204, 204, 255));
        btngrpcategory.add(rbA);
        rbA.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbA.setText("Type A");
        rbA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAActionPerformed(evt);
            }
        });

        rbC.setBackground(new java.awt.Color(204, 204, 255));
        btngrpcategory.add(rbC);
        rbC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbC.setText("Type C");
        rbC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCActionPerformed(evt);
            }
        });

        rbB.setBackground(new java.awt.Color(204, 204, 255));
        btngrpcategory.add(rbB);
        rbB.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbB.setText("Type B");
        rbB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(rbA)
                .addGap(33, 33, 33)
                .addComponent(rbB)
                .addGap(18, 18, 18)
                .addComponent(rbC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbA)
                    .addComponent(rbC)
                    .addComponent(rbB))
                .addGap(16, 16, 16))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        btnregister.setBackground(new java.awt.Color(0, 102, 0));
        btnregister.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnregister.setForeground(new java.awt.Color(255, 255, 255));
        btnregister.setText("Regsiter");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        jPanel4.add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 540, 140, 50));

        btnclear.setBackground(new java.awt.Color(0, 102, 0));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel4.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, 130, 50));

        btnpayments.setBackground(new java.awt.Color(0, 102, 0));
        btnpayments.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnpayments.setForeground(new java.awt.Color(255, 255, 255));
        btnpayments.setText("Payments");
        btnpayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaymentsActionPerformed(evt);
            }
        });
        jPanel4.add(btnpayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 140, 50));

        lblid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel4.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 170, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("DOB");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 50, 30));

        txtdob.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtdob.setText("yyyy-mm-dd");
        txtdob.setToolTipText("");
        txtdob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdobFocusGained(evt);
            }
        });
        txtdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdobActionPerformed(evt);
            }
        });
        jPanel4.add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 130, 30));

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(1030, 51));

        jLabel1.setBackground(new java.awt.Color(0, 102, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contact.png"))); // NOI18N
        jLabel1.setText("Register Student");
        jLabel1.setMinimumSize(new java.awt.Dimension(1030, 51));
        jLabel1.setPreferredSize(new java.awt.Dimension(1030, 51));

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        lbldate.setText("Date");

        btnclear1.setBackground(new java.awt.Color(0, 0, 0));
        btnclear1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnclear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 468, Short.MAX_VALUE)
                .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnclear1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnclear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbldate))))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1040, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String getStudentID() {
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/learnersms","root","");
        String sql="SELECT studentID FROM student ORDER BY studentID DESC LIMIT 1";
        PreparedStatement pstm=conn.prepareStatement(sql);
        ResultSet set = pstm.executeQuery();
        String id="S001";
        if (set.next()){
            String temp=set.getString(1);
            String[] cs = temp.split("S");
            int selectedId=Integer.parseInt(cs[1]);
            if (selectedId<10){
                id="S00"+(selectedId+1);
            }else{
                id="S0"+(selectedId+1);
            }
        }
        return id;
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    private void rbmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbmaleActionPerformed

    private void rbfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbfemaleActionPerformed

    private void rbAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAActionPerformed

    private void rbCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCActionPerformed

    private void rbBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBActionPerformed

    private void clearForm(){
        txtname.setText("");
        txtaddress.setText("");
        txtconno.setText("");
        txtnic.setText("");
        txtheight.setText("");
        txtweight.setText("");
        rbmale.setSelected(false);
        rbfemale.setSelected(false);
        rbA.setSelected(false);
        rbB.setSelected(false);
        rbC.setSelected(false);
        txtdob.setText("yyyy-mm-dd");
    }
    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        String gender="";
        if (rbmale.isSelected()) {
            gender="Male";
        }else if (rbfemale.isSelected()) {
            gender="Female";
        }else{
            JOptionPane.showMessageDialog(this,"Please select your Gender to Proceed!!!");
        }
        
        if (rbA.isSelected()) {
            category="Type A";
        }else if (rbB.isSelected()) {
            category="Type B";
        }else if (rbC.isSelected()) {
            category="Type C";
        }else{
            JOptionPane.showMessageDialog(this,"Please select the Vehicle Category to Proceed!!!");
        }
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/learnersms", "root","");
            
            String SQL="INSERT INTO student VALUES(?,?,?,?,?,?,?,?,?,?,?)";
            String sql2="INSERT INTO (paymentType,totalAmount,studentID,paidAmount,AmountToBePaid,Date) VALUES (?,?,?,?,?,?)";
            PreparedStatement pstm=conn.prepareStatement(SQL);
            PreparedStatement pstm2=conn.prepareStatement(sql2);
            pstm.setObject(1,lblid.getText());
            pstm.setObject(2,txtname.getText());
            pstm.setObject(3,txtaddress.getText());
            pstm.setObject(4,txtnic.getText());
            pstm.setObject(5,Integer.parseInt(txtconno.getText()));
            pstm.setObject(6,txtdob.getText());
            pstm.setObject(7,gender);
            pstm.setObject(8,cmbbldgrp.getSelectedItem());
            pstm.setObject(9,txtheight.getText());
            pstm.setObject(10,txtweight.getText());
            pstm.setObject(11,category);
            
            pstm2.setObject(1,PaymentForm.type);
            pstm2.setObject(2,PaymentForm.tot);
            pstm2.setObject(3,lblid.getText());
            pstm2.setObject(4,PaymentForm.payment);
            pstm2.setObject(5,PaymentForm.tobepaid);
            pstm2.setObject(6,LocalDate.now()+"");
    
            if (pstm.executeUpdate()>0) {
                if (pstm2.executeUpdate()>0) {
                    JOptionPane.showMessageDialog(this, "Student has been Reegistered Successfully!!!");
                    clearForm();
                }else{
                    JOptionPane.showMessageDialog(this, "Registration was unsuccessfull!!!");
                    PreparedStatement stm=conn.prepareStatement("DELETE FROM student WHERE studentID=?");
                    stm.setObject(1,lblid.getText());
                    stm.executeUpdate();
                    clearForm();
            }}else{
            JOptionPane.showMessageDialog(this, "Registration was unsuccessfull!!!");
                clearForm();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RegisterStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnpaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaymentsActionPerformed
        studentID=lblid.getText();
        
        if (rbA.isSelected()) {
            category="Type A";
            PaymentForm frm=new PaymentForm();
        frm.show();
        }else if (rbB.isSelected()) {
            category="Type B";
            PaymentForm frm=new PaymentForm();
        frm.show();
        }else if (rbC.isSelected()) {
            category="Type C";
            PaymentForm frm=new PaymentForm();
        frm.show();
        }else{
            JOptionPane.showMessageDialog(this,"Please select the Vehicle Category to Proceed!!!");
        }
        
        
    }//GEN-LAST:event_btnpaymentsActionPerformed

    private void txtconnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconnoActionPerformed

    private void txtdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdobActionPerformed
    }//GEN-LAST:event_txtdobActionPerformed

    private void txtdobFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdobFocusGained
        txtdob.setText("");
    }//GEN-LAST:event_txtdobFocusGained

    private void btnclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclear1ActionPerformed
        clerk.Dashboard frm=new clerk.Dashboard();
        frm.show();
        this.hide();
    }//GEN-LAST:event_btnclear1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclear1;
    private javax.swing.ButtonGroup btngrpcategory;
    private javax.swing.ButtonGroup btngrpgender;
    private javax.swing.JButton btnpayments;
    private javax.swing.JButton btnregister;
    private javax.swing.JComboBox<String> cmbbldgrp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblid;
    private javax.swing.JRadioButton rbA;
    private javax.swing.JRadioButton rbB;
    private javax.swing.JRadioButton rbC;
    private javax.swing.JRadioButton rbfemale;
    private javax.swing.JRadioButton rbmale;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtconno;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtweight;
    // End of variables declaration//GEN-END:variables
}
