/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clerk;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class StudentExam extends javax.swing.JFrame {

    String wgrade="";
    String tgrade="";
    
    /**
     * Creates new form RegisterStudent
     */
    public StudentExam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        grpwritten = new javax.swing.ButtonGroup();
        grptrial = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbwf = new javax.swing.JRadioButton();
        rbwp = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        txtwritten = new javax.swing.JTextField();
        btnregister = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnupdatew = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rbtf = new javax.swing.JRadioButton();
        rbtp = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txttrial = new javax.swing.JTextField();
        txtcategory = new javax.swing.JTextField();
        btnsavew = new javax.swing.JButton();
        btnsavet = new javax.swing.JButton();
        btnupdatet = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        btnclear1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Student ID");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 100, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Full Name");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 100, 20));

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel4.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 370, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Vehicle Category");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 160, 30));

        txtid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel4.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 110, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Written Exam Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 20))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        grpwritten.add(rbwf);
        rbwf.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbwf.setText("Fail");
        rbwf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbwfActionPerformed(evt);
            }
        });

        grpwritten.add(rbwp);
        rbwp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbwp.setText("Pass");
        rbwp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbwpActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("Date");

        txtwritten.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtwritten.setText("yyyy-mm-dd");
        txtwritten.setToolTipText("");
        txtwritten.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtwrittenFocusGained(evt);
            }
        });
        txtwritten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwrittenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(txtwritten, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(rbwp)
                .addGap(48, 48, 48)
                .addComponent(rbwf)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtwritten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbwf)
                        .addComponent(rbwp)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 590, 120));

        btnregister.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnregister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        jPanel4.add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 40, -1));

        btnclear.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear2.png"))); // NOI18N
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel4.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 70, 40));

        btnupdatew.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnupdatew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update2.png"))); // NOI18N
        btnupdatew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatewActionPerformed(evt);
            }
        });
        jPanel4.add(btnupdatew, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, 40, 39));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Written Exam Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 20))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        grptrial.add(rbtf);
        rbtf.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbtf.setText("Fail");
        rbtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtfActionPerformed(evt);
            }
        });

        grptrial.add(rbtp);
        rbtp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbtp.setText("Pass");
        rbtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtpActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setText("Date");

        txttrial.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txttrial.setText("yyyy-mm-dd");
        txttrial.setToolTipText("");
        txttrial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttrialFocusGained(evt);
            }
        });
        txttrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttrialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(txttrial, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(rbtp)
                .addGap(51, 51, 51)
                .addComponent(rbtf)
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttrial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtp)
                    .addComponent(rbtf))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 479, 590, 110));

        txtcategory.setEditable(false);
        txtcategory.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcategoryActionPerformed(evt);
            }
        });
        jPanel4.add(txtcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 160, 30));

        btnsavew.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnsavew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save2.png"))); // NOI18N
        btnsavew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavewActionPerformed(evt);
            }
        });
        jPanel4.add(btnsavew, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 40, 39));

        btnsavet.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnsavet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save2.png"))); // NOI18N
        btnsavet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavetActionPerformed(evt);
            }
        });
        jPanel4.add(btnsavet, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 40, 39));

        btnupdatet.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnupdatet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update2.png"))); // NOI18N
        btnupdatet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatetActionPerformed(evt);
            }
        });
        jPanel4.add(btnupdatet, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 40, 39));

        jPanel5.setBackground(new java.awt.Color(0, 102, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(1030, 51));

        jLabel1.setBackground(new java.awt.Color(0, 102, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exam.png"))); // NOI18N
        jLabel1.setText("Student Exam Details");
        jLabel1.setMinimumSize(new java.awt.Dimension(1030, 51));
        jLabel1.setPreferredSize(new java.awt.Dimension(1030, 51));

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        lbldate.setText("Date");

        btnclear1.setBackground(new java.awt.Color(0, 0, 0));
        btnclear1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnclear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnclear1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnclear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbldate))))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1040, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbwfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbwfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbwfActionPerformed

    private void rbwpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbwpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbwpActionPerformed

    private void clearForm(){
        txtid.setText("");
        txtname.setText("");
        txtcategory.setText("");
        txtwritten.setText("yyyy-mm-dd");
        txttrial.setText("yyyy-mm-dd");
        rbwp.setSelected(false);
        rbwf.setSelected(false);
        rbtp.setSelected(false);
        rbtf.setSelected(false);
    }
    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        search();
    }//GEN-LAST:event_btnregisterActionPerformed

    private void search(){
    try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/learnersms", "root","");
            
            String SQL="SELECT fullName,vehicleCategory FROM student WHERE studentID=?";
            PreparedStatement pstm=conn.prepareStatement(SQL);
            pstm.setObject(1,txtid.getText());
            ResultSet rst=pstm.executeQuery();
            if (rst.next()) {
                txtname.setText(rst.getString(1));
                txtcategory.setText(rst.getString(2));
                
                try{
                    //////////////////set written exam details///////////////////////////////
                    String sql2="SELECT * FROM studentwrittenexam WHERE studentID=?";
                    PreparedStatement pstm2=conn.prepareStatement(sql2);
                    pstm2.setObject(1,txtid.getText());
                    ResultSet resultSet=pstm2.executeQuery();
                    if (resultSet.next()) {
                        String getExamDate="SELECT * FROM writtenexam WHERE writtenExamID=?";
                        PreparedStatement getED=conn.prepareStatement(getExamDate);
                        getED.setObject(1,resultSet.getString(2));
                        ResultSet rstED=getED.executeQuery();
                        //txtwritten.setText(rstED.getString(2));
                        if (resultSet.getString(3).equals("Pass")){
                            rbwp.setSelected(true);
                        }else if (resultSet.getString(3).equals("Fail")){
                            rbwf.setSelected(true);
                        }

                    }else{
                    }
                }catch(Exception ex){
                      ex.printStackTrace();
                }
                    /////////////////////////////////////////////////////////////////////////////////

                    /////////////////////set trial details///////////////////////////////////////////
                try{
                    String sql2="SELECT * FROM studenttrial WHERE studentID=?";
                    PreparedStatement pstm2=conn.prepareStatement(sql2);
                    pstm2.setObject(1,txtid.getText());
                    ResultSet resultSet=pstm2.executeQuery();
                    if (resultSet.next()) {
                        String getTrialDate="SELECT date FROM trial WHERE trialID=? && category=?";
                        PreparedStatement getTD=conn.prepareStatement(getTrialDate);
                        getTD.setObject(1,resultSet.getString(2));
                        getTD.setObject(2,txtcategory.getText());
                        ResultSet rstTD=getTD.executeQuery();
                        //txttrial.setText(rstTD.getString(1));
                        if (resultSet.getString(3).equals("Pass")){
                            rbtp.setSelected(true);
                        }else if (resultSet.getString(3).equals("Fail")){
                            rbtf.setSelected(true);
                        }

                    }else{
                    }
                    ////////////////////////////////////////////////////////////////////////////
                }catch (Exception e){
                  e.printStackTrace();
                }
            }else{
            JOptionPane.showMessageDialog(this,"Student doesn't Exist!");
            }                            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdateStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UpdateStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnupdatewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatewActionPerformed
        if (rbwp.isSelected()) {
            wgrade="Pass";
        }else if (rbwf.isSelected()) {
            wgrade="Fail";
        }else{
            JOptionPane.showMessageDialog(this,"Please select the Grade to Proceed!!!");
        }
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/learnersms", "root","");
            
            String getWrittenID="SELECT writtenExamID FROM writtenexam WHERE date=?";
            PreparedStatement pstm1=conn.prepareStatement(getWrittenID);
            pstm1.setObject(1,txtwritten.getText());
            ResultSet rst=pstm1.executeQuery();
            if (rst.next()) {
                String SQL="UPDATE studentwrittenexam SET examGrade=?, examID=? WHERE studentID=?";
                PreparedStatement pstm=conn.prepareStatement(SQL);
                pstm.setObject(3,txtid.getText());
                pstm.setObject(2, rst.getString(1));
                pstm.setObject(1,wgrade);
                if (pstm.executeUpdate()>0) {
                    JOptionPane.showMessageDialog(this, "Student Exam Details has been addeds Successfully!!!");
                    clearForm();
                }
             }else{
                JOptionPane.showMessageDialog(this, "Please Check the Exam Date!!!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(StudentExam.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentExam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnupdatewActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        search();
    }//GEN-LAST:event_txtidActionPerformed

    private void txtwrittenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtwrittenFocusGained

    }//GEN-LAST:event_txtwrittenFocusGained

    private void txtwrittenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwrittenActionPerformed

    }//GEN-LAST:event_txtwrittenActionPerformed

    private void rbtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtfActionPerformed

    private void rbtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtpActionPerformed

    private void txttrialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttrialFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txttrialFocusGained

    private void txttrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttrialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttrialActionPerformed

    private void txtcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcategoryActionPerformed

    private void btnsavewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavewActionPerformed
        if (rbwp.isSelected()) {
            wgrade="Pass";
        }else if (rbwf.isSelected()) {
            wgrade="Fail";
        }else{
            JOptionPane.showMessageDialog(this,"Please select the Grade to Proceed!!!");
        }
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/learnersms", "root","");
            
            String getWrittenID="SELECT writtenExamID FROM writtenexam WHERE date=?";
            PreparedStatement pstm1=conn.prepareStatement(getWrittenID);
            pstm1.setObject(1,txtwritten.getText());
            ResultSet rst=pstm1.executeQuery();
            if (rst.next()) {
                String SQL="INSERT INTO studentwrittenexam VALUES (?,?,?)";
                PreparedStatement pstm=conn.prepareStatement(SQL);
                pstm.setObject(1,txtid.getText());
                pstm.setObject(2, rst.getString(1));
                pstm.setObject(3,wgrade);
                if (pstm.executeUpdate()>0) {
                    JOptionPane.showMessageDialog(this, "Student Exam Details has been added Successfully!!!");
                    clearForm();
                }
             }else{
                JOptionPane.showMessageDialog(this, "Please Check the Exam Date!!!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(StudentExam.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentExam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsavewActionPerformed

    private void btnsavetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavetActionPerformed
        if (rbtp.isSelected()) {
            tgrade="Pass";
        }else if (rbtp.isSelected()) {
            tgrade="Fail";
        }else{
            JOptionPane.showMessageDialog(this,"Please select the Grade to Proceed!!!");
        }
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/learnersms", "root","");
            
            String getWrittenID="SELECT trialID FROM trial WHERE date=? && category=?";
            PreparedStatement pstm1=conn.prepareStatement(getWrittenID);
            pstm1.setObject(1,txttrial.getText());
            pstm1.setObject(2, txtcategory.getText());
            ResultSet rst=pstm1.executeQuery();
            if (rst.next()) {
                String SQL="INSERT INTO studenttrial VALUES (?,?,?)";
                PreparedStatement pstm=conn.prepareStatement(SQL);
                pstm.setObject(1,txtid.getText());
                pstm.setObject(2, rst.getString(1));
                pstm.setObject(3,tgrade);
                if (pstm.executeUpdate()>0) {
                    JOptionPane.showMessageDialog(this, "Student Details has been added Successfully!!!");
                    clearForm();
                }
             }else{
                JOptionPane.showMessageDialog(this, "Please check the Exam Date!!!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(StudentExam.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentExam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsavetActionPerformed

    private void btnupdatetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatetActionPerformed
        if (rbtp.isSelected()) {
            tgrade="Pass";
        }else if (rbtp.isSelected()) {
            tgrade="Fail";
        }else{
            JOptionPane.showMessageDialog(this,"Please select the Grade to Proceed!!!");
        }
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/learnersms", "root","");
            
            String getWrittenID="SELECT trialID FROM trial WHERE date=? && category=?";
            PreparedStatement pstm1=conn.prepareStatement(getWrittenID);
            pstm1.setObject(1,txttrial.getText());
            pstm1.setObject(2, txtcategory.getText());
            ResultSet rst=pstm1.executeQuery();
            if (rst.next()) {
                String SQL="UPDATE studenttrial SET trialID=?, trialGrade=? WHERE studentID=?";
                PreparedStatement pstm=conn.prepareStatement(SQL);
                pstm.setObject(3,txtid.getText());
                pstm.setObject(1, rst.getString(1));
                pstm.setObject(2,tgrade);
                if (pstm.executeUpdate()>0) {
                    JOptionPane.showMessageDialog(this, "Student Details has been added Successfully!!!");
                    clearForm();
                }
             }else{
                JOptionPane.showMessageDialog(this, "Please check the Exam Date!!!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(StudentExam.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentExam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnupdatetActionPerformed

    private void btnclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclear1ActionPerformed
        clerk.Dashboard frm=new clerk.Dashboard();
        frm.show();
        this.hide();
    }//GEN-LAST:event_btnclear1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclear1;
    private javax.swing.JButton btnregister;
    private javax.swing.JButton btnsavet;
    private javax.swing.JButton btnsavew;
    private javax.swing.JButton btnupdatet;
    private javax.swing.JButton btnupdatew;
    private javax.swing.ButtonGroup grptrial;
    private javax.swing.ButtonGroup grpwritten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JRadioButton rbtf;
    private javax.swing.JRadioButton rbtp;
    private javax.swing.JRadioButton rbwf;
    private javax.swing.JRadioButton rbwp;
    private javax.swing.JTextField txtcategory;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txttrial;
    private javax.swing.JTextField txtwritten;
    // End of variables declaration//GEN-END:variables
}
