/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clerk;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class UpdateStudent extends javax.swing.JFrame {

    /**
     * Creates new form RegisterStudent
     */
    public UpdateStudent() {
        initComponents();
    }
    public static String category="";
    public static String id="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        grpgender = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtheight = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbbldgrp = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtweight = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbmale = new javax.swing.JRadioButton();
        rbfemale = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbA = new javax.swing.JRadioButton();
        rbC = new javax.swing.JRadioButton();
        rbB = new javax.swing.JRadioButton();
        btnregister = new javax.swing.JButton();
        btnpayments = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        txtconno1 = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        btnclear1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Student ID");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 110, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Full Name");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, 30));

        txtname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel4.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 370, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Address");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 70, 30));

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 350, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Contact No");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 100, 30));

        txtid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel4.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("NIC");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 50, 30));

        txtheight.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel4.add(txtheight, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 60, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Blood Group");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 110, 30));

        cmbbldgrp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cmbbldgrp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        jPanel4.add(cmbbldgrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 107, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Height(ft)");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 100, 30));

        txtweight.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel4.add(txtweight, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, 60, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        rbmale.setBackground(new java.awt.Color(204, 204, 255));
        grpgender.add(rbmale);
        rbmale.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbmale.setText("Male");
        rbmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmaleActionPerformed(evt);
            }
        });

        rbfemale.setBackground(new java.awt.Color(204, 204, 255));
        grpgender.add(rbfemale);
        rbfemale.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbfemale.setText("Female");
        rbfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfemaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(rbmale)
                .addGap(26, 26, 26)
                .addComponent(rbfemale)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbmale)
                    .addComponent(rbfemale))
                .addGap(16, 16, 16))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Weight(kg)");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 100, 30));

        txtnic.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel4.add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 210, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Vehicle Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        rbA.setBackground(new java.awt.Color(204, 204, 255));
        rbA.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbA.setText("Type A");
        rbA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAActionPerformed(evt);
            }
        });

        rbC.setBackground(new java.awt.Color(204, 204, 255));
        rbC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbC.setText("Type C");
        rbC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCActionPerformed(evt);
            }
        });

        rbB.setBackground(new java.awt.Color(204, 204, 255));
        rbB.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rbB.setText("Type B");
        rbB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(rbA)
                .addGap(33, 33, 33)
                .addComponent(rbB)
                .addGap(18, 18, 18)
                .addComponent(rbC)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbA)
                    .addComponent(rbC)
                    .addComponent(rbB))
                .addGap(16, 16, 16))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        btnregister.setBackground(new java.awt.Color(0, 102, 0));
        btnregister.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnregister.setText("Update");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        jPanel4.add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 530, 140, 50));

        btnpayments.setBackground(new java.awt.Color(0, 102, 0));
        btnpayments.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnpayments.setText("Payments");
        btnpayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaymentsActionPerformed(evt);
            }
        });
        jPanel4.add(btnpayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, 140, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("DOB");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 70, 30));

        txtdob.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtdob.setText("yyyy-mm-dd");
        txtdob.setToolTipText("");
        txtdob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdobFocusGained(evt);
            }
        });
        txtdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdobActionPerformed(evt);
            }
        });
        jPanel4.add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 130, 30));

        txtconno1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtconno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconno1ActionPerformed(evt);
            }
        });
        jPanel4.add(txtconno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 160, 30));

        btnsearch.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel4.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 40, 30));

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(1030, 51));

        jLabel11.setBackground(new java.awt.Color(0, 102, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contact.png"))); // NOI18N
        jLabel11.setText("Update Student Details");
        jLabel11.setMinimumSize(new java.awt.Dimension(1030, 51));
        jLabel11.setPreferredSize(new java.awt.Dimension(1030, 51));

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbldate.setForeground(new java.awt.Color(255, 255, 255));
        lbldate.setText("Date");

        btnclear1.setBackground(new java.awt.Color(0, 0, 0));
        btnclear1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnclear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 393, Short.MAX_VALUE)
                .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnclear1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnclear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbldate))))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1040, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbmaleActionPerformed

    private void rbfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbfemaleActionPerformed

    private void rbAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAActionPerformed

    private void rbCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCActionPerformed

    private void rbBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBActionPerformed

    private void clearForm(){
        txtname.setText("");
        txtaddress.setText("");
        txtid.setText("");
        txtnic.setText("");
        txtheight.setText("");
        txtweight.setText("");
        rbmale.setSelected(false);
        rbfemale.setSelected(false);
        rbA.setSelected(false);
        rbB.setSelected(false);
        rbC.setSelected(false);
        txtdob.setText("yyyy-mm-dd");
        txtid.setText("");
    }
    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        String gender="";
        String category="";
        if (rbmale.isSelected()) {
            gender="Male";
        }else if (rbfemale.isSelected()) {
            gender="Female";
        }else{
            JOptionPane.showMessageDialog(this,"Please select your Gender to Proceed!!!");
        }
        
        if (rbA.isSelected()) {
            category="Type A";
        }else if (rbB.isSelected()) {
            category="Type B";
        }else if (rbC.isSelected()) {
            category="Type C";
        }else{
            JOptionPane.showMessageDialog(this,"Please select the Vehicle Category to Proceed!!!");
        }
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/learnersms", "root","");
            
            String SQL="UPDATE student SET fullName=?,address=?,nic=?,contactNo=?,dob=?,gender=?,bloodgrp=?,height=?,weight=?,vehicleCategory=? WHERE studentID=?";
            PreparedStatement pstm=conn.prepareStatement(SQL);
            pstm.setObject(1,txtname.getText());
            pstm.setObject(2,txtaddress.getText());
            pstm.setObject(3,txtnic.getText());
            pstm.setObject(4,Integer.parseInt(txtconno1.getText()));
            pstm.setObject(5,txtdob.getText());
            pstm.setObject(6,gender);
            pstm.setObject(7,cmbbldgrp.getSelectedItem());
            pstm.setObject(8,txtheight.getText());
            pstm.setObject(9,txtweight.getText());
            pstm.setObject(10,category);
            pstm.setObject(11,txtid.getText());
    
            if (pstm.executeUpdate()>0) {
                JOptionPane.showMessageDialog(this, "Student Details has been Updated Successfully!!!");
                clearForm();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(UpdateStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdateStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btnpaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaymentsActionPerformed
        id=txtid.getText();
        if (rbA.isSelected()) {
            category="Type A";
            UpdatePaymentForm frm=new UpdatePaymentForm();
            frm.show();
        }else if (rbB.isSelected()) {
            category="Type B";
            UpdatePaymentForm frm=new UpdatePaymentForm();
        frm.show();
        }else if (rbC.isSelected()) {
            category="Type C";
            UpdatePaymentForm frm=new UpdatePaymentForm();
        frm.show();
        }else{
            JOptionPane.showMessageDialog(this,"Please select the Vehicle Category to Proceed!!!");
        }
    }//GEN-LAST:event_btnpaymentsActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        search();
    }//GEN-LAST:event_txtidActionPerformed

    private void txtdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdobActionPerformed
    }//GEN-LAST:event_txtdobActionPerformed

    private void txtdobFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdobFocusGained
        txtdob.setText("");
    }//GEN-LAST:event_txtdobFocusGained

    private void search(){
     try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/learnersms", "root","");
            
            String SQL="SELECT * FROM student WHERE studentID=?";
            PreparedStatement pstm=conn.prepareStatement(SQL);
            pstm.setObject(1,txtid.getText());
            ResultSet rst=pstm.executeQuery();
            if (rst.next()) {
                txtname.setText(rst.getString(2));
                txtaddress.setText(rst.getString(3));
                txtnic.setText(rst.getString(4));
                txtconno1.setText(rst.getString(5)+"");
                txtdob.setText(rst.getString(6));
                if (rst.getString(7).equals("Male")) {
                    rbmale.setSelected(true);
                }else if (rst.getString(7).equals("Female")) {
                    rbfemale.setSelected(true);
                }
                cmbbldgrp.setSelectedItem(rst.getString(8));
                txtheight.setText(rst.getString(9));
                txtweight.setText(rst.getString(10));
                if (rst.getString(11).equals("Type A")) {
                    rbA.setSelected(true);
                }else if (rst.getString(11).equals("Type B")) {
                    rbB.setSelected(true);
                }else if (rst.getString(11).equals("Type C")) {
                    rbC.setSelected(true);
                }
            }else{
            JOptionPane.showMessageDialog(this,"Student doesn't Exist!");
            }                            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdateStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UpdateStudent.class.getName()).log(Level.SEVERE, null, ex);
        }}
    
    private void txtconno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconno1ActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        search();
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclear1ActionPerformed
        clerk.Dashboard frm=new clerk.Dashboard();
        frm.show();
        this.hide();
    }//GEN-LAST:event_btnclear1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear1;
    private javax.swing.JButton btnpayments;
    private javax.swing.JButton btnregister;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox<String> cmbbldgrp;
    private javax.swing.ButtonGroup grpgender;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JRadioButton rbA;
    private javax.swing.JRadioButton rbB;
    private javax.swing.JRadioButton rbC;
    private javax.swing.JRadioButton rbfemale;
    private javax.swing.JRadioButton rbmale;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtconno1;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtweight;
    // End of variables declaration//GEN-END:variables
}
